import 'package:get/get_navigation/src/root/internacionalization.dart';

class Multi_Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //------------------------en_US
        'en_US': {
          'zalada': 'Zalada',
          "onboard_heading_one": "Find the item you've been looking for",
          "onboard_one_description":
              "Here you'll see rich varieties of goods, carefully classified for seamless browsing experience",
          "skip": "Skip",
          "onboard_heading_two": "Get those shopping bags filled",
          "onboard_two_description":
              "Add any item you want to your cart or save it on your wishlist, so you don't miss it in your future purchase.",
          "onboard_heading_three": "Fast & Secure payment",
          "onboard_three_description":
              "There are many payment options available to speed up and simplify your payment process.",
          "verfication_code": "Verification code",
          "otp_description":
              "We have sent the code verification to you WhatsApp Number",
          "otp": "OTP",
          "continue": "Continue",
          "recent_code": "Recent code in ",
          "resend_code": "Resend OTP",
          "congratulation": "Congratulations!",
          "congratulation_bar_description":
              "Your account is ready to use. You will be redirected to the Homepage in a few seconds.",
          "filter": "Filter",
          "reset": "Reset",
          "apply_filter": "Apply Filter",
          "price_range": "Price Range",
          "sort_by": "Sort by",
          "new_arrived": "New Arrived",
          "higher_price": "Higher Price",
          "lower_price": "Lower Price",
          "discount": "Discount",
          "order_successfull": "Order Successful!",
          "view_order": "View Order",
          "successfull_bar_description": "Your have successfully made order",
          "Wishlist": "Wishlist",
          "Brower": "Brower",
          "Home": "Home",
          "Cart": "Cart",
          "Profile": "Profile",
          "search_product": "Search laptop, headset, etc...",
          "home_card_description": "Find best device for your setup!",
          "hot_deal": "Hot deals🔥",
          "space_grey": "Space Grey",
          "available_storage": "Available Storage",
          "gallery": "Gallery",
          "product_descritpion": "Product Description",
          "read_more": "Read More",
          "read_less": "Read Less",
          "product_related": "Product Related",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
        }
      };
}
