import 'package:get/get_navigation/src/root/internacionalization.dart';

class Multi_Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        //------------------------en_US
        'en_US': {
          'zalada': 'Zalada',
          "onboard_heading_one": "Find the item you've been looking for",
          "onboard_one_description":
              "Here you'll see rich varieties of goods, carefully classified for seamless browsing experience",
          "skip": "Skip",
          "onboard_heading_two": "Get those shopping bags filled",
          "onboard_two_description":
              "Add any item you want to your cart or save it on your wishlist, so you don't miss it in your future purchase.",
          "onboard_heading_three": "Fast & Secure payment",
          "onboard_three_description":
              "There are many payment options available to speed up and simplify your payment process.",
          "verfication_code": "Verification code",
          "otp_description":
              "We have sent the code verification to you WhatsApp Number",
          "otp": "OTP",
          "continue": "Continue",
          "recent_code": "Recent code in ",
          "resend_code": "Resend OTP",
          "congratulation": "Congratulations!",
          "congratulation_bar_description": "Your account is ready to use. You will be redirected to the Homepage in a few seconds.",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
          "": "",
        }
      };
}
